#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
//2.06寸 amoled
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

//===================espwatch-amoled-4g v1.1
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_21
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_14
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_18
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_17
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_13
  
#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define POWER_BUTTON_GPIO       GPIO_NUM_46

#define EXAMPLE_PIN_NUM_LCD_CS    GPIO_NUM_40
#define EXAMPLE_PIN_NUM_LCD_PCLK  GPIO_NUM_5
#define EXAMPLE_PIN_NUM_LCD_DATA0 GPIO_NUM_6
#define EXAMPLE_PIN_NUM_LCD_DATA1 GPIO_NUM_7
#define EXAMPLE_PIN_NUM_LCD_DATA2 GPIO_NUM_12
#define EXAMPLE_PIN_NUM_LCD_DATA3 GPIO_NUM_42
#define EXAMPLE_PIN_NUM_LCD_RST   GPIO_NUM_4
#define DISPLAY_WIDTH 410
#define DISPLAY_HEIGHT 502
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

// 触摸屏I2C引脚定义
#define EXAMPLE_PIN_NUM_TOUCH_INT         GPIO_NUM_39
#define EXAMPLE_PIN_NUM_TOUCH_RST         GPIO_NUM_38

#define DISPLAY_EN_PIN            GPIO_NUM_47
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define ML307_RX_PIN GPIO_NUM_44
#define ML307_TX_PIN GPIO_NUM_43
#define ML307_EN_PIN GPIO_NUM_10

#endif // _BOARD_CONFIG_H_
