#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

//====================espwatch-s3a3 1.69寸 16pin
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_21
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_18
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_17
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_12

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_39
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define POWER_BUTTON_GPIO       GPIO_NUM_45
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SDA_PIN             AUDIO_CODEC_I2C_SDA_PIN
#define DISPLAY_SCL_PIN             AUDIO_CODEC_I2C_SCL_PIN

#define DISPLAY_MISO_PIN            GPIO_NUM_NC
#define DISPLAY_MOSI_PIN            GPIO_NUM_5
#define DISPLAY_SCLK_PIN            GPIO_NUM_7
#define DISPLAY_CS_PIN              GPIO_NUM_8
#define DISPLAY_DC_PIN              GPIO_NUM_6
#define DISPLAY_RESET_PIN           GPIO_NUM_4
#define DISPLAY_BACKLIGHT_PIN       GPIO_NUM_14

#define VIB_MOTOR_PIN       GPIO_NUM_9

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  280
#define DISPLAY_SWAP_XY false
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  20

#endif // _BOARD_CONFIG_H_
