#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

//====================espwatch-s3b3
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_21
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_15
#define AUDIO_I2S_GPIO_WS GPIO_NUM_16
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_17
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_18

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define POWER_BUTTON_GPIO       GPIO_NUM_45
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SDA_PIN             AUDIO_CODEC_I2C_SDA_PIN
#define DISPLAY_SCL_PIN             AUDIO_CODEC_I2C_SCL_PIN
// #define LCD_TYPE_JD9853_SERIAL    // 使用JD9853串口屏
#define DISPLAY_MISO_PIN            GPIO_NUM_NC
#define DISPLAY_MOSI_PIN            GPIO_NUM_6
#define DISPLAY_SCLK_PIN            GPIO_NUM_5
#define DISPLAY_CS_PIN              GPIO_NUM_12
#define DISPLAY_DC_PIN              GPIO_NUM_11
#define DISPLAY_RESET_PIN           GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_PIN       GPIO_NUM_47

#define VIB_MOTOR_PIN       GPIO_NUM_4

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  284
#define DISPLAY_SWAP_XY false
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#endif // _BOARD_CONFIG_H_
